# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

disclapglm_linkfun <- function(mu) {
    .Call('disclapmix_disclapglm_linkfun', PACKAGE = 'disclapmix', mu)
}

disclapglm_linkinv <- function(eta) {
    .Call('disclapmix_disclapglm_linkinv', PACKAGE = 'disclapmix', eta)
}

disclapglm_mu_eta <- function(eta) {
    .Call('disclapmix_disclapglm_mu_eta', PACKAGE = 'disclapmix', eta)
}

disclapglm_varfunc <- function(mu) {
    .Call('disclapmix_disclapglm_varfunc', PACKAGE = 'disclapmix', mu)
}

disclapglm_loglikeh <- function(mu, y) {
    .Call('disclapmix_disclapglm_loglikeh', PACKAGE = 'disclapmix', mu, y)
}

disclapglm_deviance <- function(y, mu, wt) {
    .Call('disclapmix_disclapglm_deviance', PACKAGE = 'disclapmix', y, mu, wt)
}

rcpp_create_design_matrix <- function(x, clusters) {
    .Call('disclapmix_rcpp_create_design_matrix', PACKAGE = 'disclapmix', x, clusters)
}

rcpp_create_new_weight_vector <- function(vic, loci) {
    .Call('disclapmix_rcpp_create_new_weight_vector', PACKAGE = 'disclapmix', vic, loci)
}

rcpp_create_response_vector <- function(x, y) {
    .Call('disclapmix_rcpp_create_response_vector', PACKAGE = 'disclapmix', x, y)
}

rcpp_calculate_wic <- function(x, y, p, tau) {
    .Call('disclapmix_rcpp_calculate_wic', PACKAGE = 'disclapmix', x, y, p, tau)
}

rcpp_calculate_vic <- function(wic) {
    .Call('disclapmix_rcpp_calculate_vic', PACKAGE = 'disclapmix', wic)
}

rcpp_calculate_haplotype_probabilities <- function(new_data, y, p, tau) {
    .Call('disclapmix_rcpp_calculate_haplotype_probabilities', PACKAGE = 'disclapmix', new_data, y, p, tau)
}

